name: BENV0119
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - sktime
  - statsmodels
  - numpy
  - scipy
  - seaborn
  - jupyter
  - scikit-learn
  - pandas
  - openpyxl
  - python
